--- #YAML:1.0
name:                XML-Amazon
version:             0.03
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Data::Dumper:                  0
    LWP::Simple:                   0
    URI::Escape:                   0
    XML::Simple:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
