# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-Amazon
version:      0.02
version_from: lib/XML/Amazon.pm
installdirs:  site
requires:
    Data::Dumper:                  0
    LWP::Simple:                   0
    URI::Escape:                   0
    XML::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
