---
author: ~
configure_requires:
  ExtUtils::MakeMaker: 6.44
distribution_type: module
generated_by: 'Module::Install version 0.750'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
module_name: XML::Amazon
name: XML-Amazon
no_index:
  directory:
    - inc
    - t
requires:
  Data::Dumper: 0
  LWP::Simple: 0
  URI::Escape: 0
  XML::Simple: 0
version: 0.04
